### PR TITLE
Fix version number and homepage

### PR DESCRIPTION
**Pull request by TriforceOfKirby**
A version number of 1.2.0x is invalid.

### CODE REVIEW

**Comment by AmeliaBR** [comment]
Sure, why not.  I wasn't planning on keeping a parallel repository, just to update Peter Flynn's version, but since he hasn't been merging pull requests I might as well make this a full-fledged fork.  Although the version number should still be an increment from 1.2.0

That said, I've actually disabled this extension myself because of the major stability issues when including scripts in SVG.  When I have some time, I'll be planning to do a complete refactoring to use embedded objects instead of inline SVG.

**Comment by TriforceOfKirby** [comment]
Yeah maybe change the version number to 1.2.1?

The main reason I wanted to use this fork was because of the viewBox/size bugs, but the invalid version number prevented adding it to Brackets.

**Comment by AmeliaBR** [comment]
I already incremented the version to 1.2.1, so it should be good to go.  Let me know if there are any other complaints from Brackets.

As for security, just be sure to disable the extension if using any SVG with scripts, since they end up running in the main Brackets thread every time you edit (and freeze everything if there's a fatal error or infinite loop).  Also, style blocks apply to the entire Brackets window, which can be wonky.  If you're just editing simple SVG icons, it's great!

**Comment by TriforceOfKirby** [comment]
I generally don't use any SVGs with scripts, so I should be fine. I've been mostly playing with SMIL animations lately which seem to work perfectly fine with this extension.

**Comment by AmeliaBR** [comment]
P.S. @TriforceOfKirby 

Peter Flynn has just released a 1.3.0 that includes my fixes and a few more.

**Comment by TriforceOfKirby** [comment]
Oh cool, thanks for letting me know!

**Pull request merged**
